spring.application.name=sistema_tic

# =========================================================
# PERFIL ACTIVO (Por defecto 'local' si no se especifica)
# En Render / Producción configurar: SPRING_PROFILES_ACTIVE=prod
# =========================================================
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

# =========================================================
# SERVIDOR (Puerto dinámico para Render o local)
# =========================================================
server.port=${PORT:8081}

# =========================================================
# CONFIGURACIÓN GENERAL JPA / HIBERNATE
# =========================================================
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
