spring.application.name=sistema_tic

# Conexión a PostgreSQL
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/sistema_tics}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:1234}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Thymeleaf
spring.thymeleaf.cache=false

# Servidor
server.port=${PORT:8080}

# RESPALDOS
backup.enabled=true
backup.directory=backups
backup.pg-dump-path=${PG_DUMP_PATH:C:/Program Files/PostgreSQL/18/bin/pg_dump.exe}
backup.database.host=${DB_HOST:localhost}
backup.database.port=${DB_PORT:5432}
backup.database.name=${DB_NAME:sistema_tics}
backup.database.username=${DB_USERNAME:postgres}
backup.database.password=${DB_PASSWORD:1234}

# JWT
jwt.secret=${JWT_SECRET:RkFzZTRfU0lTVEVNQV9USUNfU0VDUkVUXzIwMjZfU0VHVVJPUw==}
